# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BED4OggKuGJ7Zr3KMc-4jxCxCbdZzukO
"""

import pandas as pd
teacher=pd.DataFrame({
    'FISH' :['Qadamova Z' , "Karimov S" , 'Raxmonov O' , "Xusanova M" ,"Azizov I" ,"Ibragimov N" ,"Ibragimov N" ,"Ibragimov N" ,"To'rayeva M" , "To'rayeva M"],
    "Fani" :["Sun'iy intellekt asoslari" , "Sun'iy intellekt asoslari" , "Kiberxavfsizlik asoslari", "Kiberxavfsizlik asoslari" , "Buxgalteriya hisobi" , "Buxgalteriya hisobi" , "Mikroiqtisodiyot" , "Mikroiqtisodiyot" , "Sotib olish" , "Sotib olish"],
    "Mashgulot turi" :['Amaliy' , "Ma'ruza" , 'Amaliy' , "Ma'ruza" , 'Amaliy' , "Ma'ruza" , 'Amaliy' , "Ma'ruza" , 'Amaliy' , "Ma'ruza"],
    "Kafedarasi" :["Axborot texnologiyalari" , "Axborot texnologiyalari" , "Axborot texnologiyalari" , "Axborot texnologiyalari" , "Axborot texnologiyalari" , "Axborot texnologiyalari" , "Axborot texnologiyalari" , "Axborot texnologiyalari" , "Axborot texnologiyalari" , "Axborot texnologiyalari"],
})
print(teacher)

teacher.to_excel("660-guruh teacher's.xlsx")